
production:
  label.encounter.map: UPDATE OUTCOME MUM|UPDATE OUTCOME,BABY DELIVERY COUNT|BABY DELIVERY,ADMIT BABY|ADMIT PATIENT,KANGAROO REVIEW VISIT|KANGAROO REVIEW VISIT,BABY|OUTCOME,UPDATE BABY OUTCOME|UPDATE BABY OUTCOME,ADMIT PATIENT|ADMIT PATIENT,BABY DELIVERY|BABY DELIVERY,MOTHER|OUTCOME
  clinical.encounters.sequential.list: ADMIT PATIENT,UPDATE OUTCOME MUM,ADMIT BABY,BABY DELIVERY,UPDATE BABY OUTCOME,KANGAROO REVIEW VISIT
  clinical.encounters.display.list: MOTHER|ADMIT PATIENT,UPDATE OUTCOME MUM;BABY|ADMIT BABY,BABY DELIVERY,UPDATE BABY OUTCOME,KANGAROO REVIEW VISIT
  scope: BABY|,BABY DELIVERY COUNT|EXISTS,MOTHER|,BABY DELIVERY|,UPDATE BABY OUTCOME|,UPDATE OUTCOME MUM|,ADMIT PATIENT|,ADMIT BABY|,KANGAROO REVIEW VISIT|
  concept: BABY DELIVERY COUNT|Number of babies
  label: MOTHER|Mother,UPDATE OUTCOME MUM|Update Outcome Mum,BABY DELIVERY|Baby Delivery,ADMIT BABY|Admit baby,BABY DELIVERY COUNT|Baby Delivery Count,BABY|Baby

development:
  label.encounter.map: UPDATE OUTCOME MUM|UPDATE OUTCOME,BABY DELIVERY COUNT|BABY DELIVERY,ADMIT BABY|ADMIT PATIENT,KANGAROO REVIEW VISIT|KANGAROO REVIEW VISIT,BABY|OUTCOME,UPDATE BABY OUTCOME|UPDATE BABY OUTCOME,ADMIT PATIENT|ADMIT PATIENT,BABY DELIVERY|BABY DELIVERY,MOTHER|OUTCOME
  clinical.encounters.sequential.list: ADMIT PATIENT,UPDATE OUTCOME MUM,ADMIT BABY,BABY DELIVERY,UPDATE BABY OUTCOME,KANGAROO REVIEW VISIT
  clinical.encounters.display.list: MOTHER|ADMIT PATIENT,UPDATE OUTCOME MUM;BABY|ADMIT BABY,BABY DELIVERY,UPDATE BABY OUTCOME,KANGAROO REVIEW VISIT
  scope: BABY|,BABY DELIVERY COUNT|EXISTS,MOTHER|,BABY DELIVERY|,UPDATE BABY OUTCOME|,UPDATE OUTCOME MUM|,ADMIT PATIENT|,ADMIT BABY|,KANGAROO REVIEW VISIT|
  concept: BABY DELIVERY COUNT|Number of babies
  label: MOTHER|Mother,UPDATE OUTCOME MUM|Update Outcome Mum,BABY DELIVERY|Baby Delivery,ADMIT BABY|Admit baby,BABY DELIVERY COUNT|Baby Delivery Count,BABY|Baby

test: &TEST
  label.encounter.map: UPDATE OUTCOME MUM|UPDATE OUTCOME,BABY DELIVERY COUNT|BABY DELIVERY,ADMIT BABY|ADMIT PATIENT,KANGAROO REVIEW VISIT|KANGAROO REVIEW VISIT,BABY|OUTCOME,UPDATE BABY OUTCOME|UPDATE BABY OUTCOME,ADMIT PATIENT|ADMIT PATIENT,BABY DELIVERY|BABY DELIVERY,MOTHER|OUTCOME
  clinical.encounters.sequential.list: ADMIT PATIENT,UPDATE OUTCOME MUM,ADMIT BABY,BABY DELIVERY,UPDATE BABY OUTCOME,KANGAROO REVIEW VISIT
  clinical.encounters.display.list: MOTHER|ADMIT PATIENT,UPDATE OUTCOME MUM;BABY|ADMIT BABY,BABY DELIVERY,UPDATE BABY OUTCOME,KANGAROO REVIEW VISIT
  scope: BABY|,BABY DELIVERY COUNT|EXISTS,MOTHER|,BABY DELIVERY|,UPDATE BABY OUTCOME|,UPDATE OUTCOME MUM|,ADMIT PATIENT|,ADMIT BABY|,KANGAROO REVIEW VISIT|
  concept: BABY DELIVERY COUNT|Number of babies
  label: MOTHER|Mother,UPDATE OUTCOME MUM|Update Outcome Mum,BABY DELIVERY|Baby Delivery,ADMIT BABY|Admit baby,BABY DELIVERY COUNT|Baby Delivery Count,BABY|Baby

