
production:
  label.encounter.map: MOTHER|OUTCOME,UPDATE BABY OUTCOME|UPDATE BABY OUTCOME,UPDATE OUTCOME MUM|UPDATE OUTCOME,BABY DELIVERY|BABY DELIVERY,ADMIT PATIENT|ADMIT PATIENT,ADMIT BABY|ADMIT PATIENT,KANGAROO REVIEW VISIT|KANGAROO REVIEW VISIT,REFER BABY|REFERRAL,BABY|OUTCOME
  clinical.encounters.sequential.list: ADMIT PATIENT,UPDATE OUTCOME MUM,ADMIT BABY,BABY DELIVERY,REFER BABY,UPDATE BABY OUTCOME,KANGAROO REVIEW VISIT
  clinical.encounters.display.list: MOTHER|ADMIT PATIENT,UPDATE OUTCOME MUM;BABY|ADMIT BABY,BABY DELIVERY,REFER BABY,UPDATE BABY OUTCOME,KANGAROO REVIEW VISIT
  scope: UPDATE BABY OUTCOME|,REFER BABY|,MOTHER|,BABY|,KANGAROO REVIEW VISIT|,UPDATE OUTCOME MUM|,ADMIT PATIENT|,BABY DELIVERY|,ADMIT BABY|
  label: BABY|Baby,REFER BABY|Refer Baby,ADMIT BABY|Admit baby,UPDATE OUTCOME MUM|Update Outcome Mum,BABY DELIVERY|Baby Delivery,MOTHER|Mother

development:
  label.encounter.map: MOTHER|OUTCOME,UPDATE BABY OUTCOME|UPDATE BABY OUTCOME,UPDATE OUTCOME MUM|UPDATE OUTCOME,BABY DELIVERY|BABY DELIVERY,ADMIT PATIENT|ADMIT PATIENT,ADMIT BABY|ADMIT PATIENT,KANGAROO REVIEW VISIT|KANGAROO REVIEW VISIT,REFER BABY|REFERRAL,BABY|OUTCOME
  clinical.encounters.sequential.list: ADMIT PATIENT,UPDATE OUTCOME MUM,ADMIT BABY,BABY DELIVERY,REFER BABY,UPDATE BABY OUTCOME,KANGAROO REVIEW VISIT
  clinical.encounters.display.list: MOTHER|ADMIT PATIENT,UPDATE OUTCOME MUM;BABY|ADMIT BABY,BABY DELIVERY,REFER BABY,UPDATE BABY OUTCOME,KANGAROO REVIEW VISIT
  scope: UPDATE BABY OUTCOME|,REFER BABY|,MOTHER|,BABY|,KANGAROO REVIEW VISIT|,UPDATE OUTCOME MUM|,ADMIT PATIENT|,BABY DELIVERY|,ADMIT BABY|
  label: BABY|Baby,REFER BABY|Refer Baby,ADMIT BABY|Admit baby,UPDATE OUTCOME MUM|Update Outcome Mum,BABY DELIVERY|Baby Delivery,MOTHER|Mother

test: &TEST
  label.encounter.map: MOTHER|OUTCOME,UPDATE BABY OUTCOME|UPDATE BABY OUTCOME,UPDATE OUTCOME MUM|UPDATE OUTCOME,BABY DELIVERY|BABY DELIVERY,ADMIT PATIENT|ADMIT PATIENT,ADMIT BABY|ADMIT PATIENT,KANGAROO REVIEW VISIT|KANGAROO REVIEW VISIT,REFER BABY|REFERRAL,BABY|OUTCOME
  clinical.encounters.sequential.list: ADMIT PATIENT,UPDATE OUTCOME MUM,ADMIT BABY,BABY DELIVERY,REFER BABY,UPDATE BABY OUTCOME,KANGAROO REVIEW VISIT
  clinical.encounters.display.list: MOTHER|ADMIT PATIENT,UPDATE OUTCOME MUM;BABY|ADMIT BABY,BABY DELIVERY,REFER BABY,UPDATE BABY OUTCOME,KANGAROO REVIEW VISIT
  scope: UPDATE BABY OUTCOME|,REFER BABY|,MOTHER|,BABY|,KANGAROO REVIEW VISIT|,UPDATE OUTCOME MUM|,ADMIT PATIENT|,BABY DELIVERY|,ADMIT BABY|
  label: BABY|Baby,REFER BABY|Refer Baby,ADMIT BABY|Admit baby,UPDATE OUTCOME MUM|Update Outcome Mum,BABY DELIVERY|Baby Delivery,MOTHER|Mother

mother: two_protocol_patients
admit_patient: two_protocol_patients
update_outcome_mum: two_protocol_patients
baby: two_protocol_patients
admit_baby: two_protocol_patients
baby_delivery: two_protocol_patients
refer_baby: two_protocol_patients
update_baby_outcome: two_protocol_patients
kangaroo_review_visit: two_protocol_patients