
production:
  label.encounter.map: UPDATE BABY OUTCOME|UPDATE BABY OUTCOME,BABY DELIVERY COUNT|BABY DELIVERY,ADMIT BABY|ADMIT PATIENT,UPDATE OUTCOME MUM|UPDATE OUTCOME,BABY|OUTCOME,KANGAROO REVIEW VISIT|KANGAROO REVIEW VISIT,BABY DELIVERY|BABY DELIVERY,MOTHER|OUTCOME,ADMIT PATIENT|ADMIT PATIENT
  clinical.encounters.sequential.list: ADMIT PATIENT,UPDATE OUTCOME MUM,ADMIT BABY,BABY DELIVERY,UPDATE BABY OUTCOME,KANGAROO REVIEW VISIT
  clinical.encounters.display.list: MOTHER|ADMIT PATIENT,UPDATE OUTCOME MUM;BABY|ADMIT BABY,BABY DELIVERY,UPDATE BABY OUTCOME,KANGAROO REVIEW VISIT
  scope: UPDATE OUTCOME MUM|,BABY DELIVERY|,BABY|,UPDATE BABY OUTCOME|,MOTHER|,ADMIT BABY|,KANGAROO REVIEW VISIT|,ADMIT PATIENT|,BABY DELIVERY COUNT|EXISTS
  concept: BABY DELIVERY COUNT|Number of babies
  label: ADMIT BABY|Admit baby,BABY DELIVERY|Baby Delivery,BABY|Baby,BABY DELIVERY COUNT|Baby Delivery Count,UPDATE OUTCOME MUM|Update Outcome Mum,MOTHER|Mother

development:
  label.encounter.map: UPDATE BABY OUTCOME|UPDATE BABY OUTCOME,BABY DELIVERY COUNT|BABY DELIVERY,ADMIT BABY|ADMIT PATIENT,UPDATE OUTCOME MUM|UPDATE OUTCOME,BABY|OUTCOME,KANGAROO REVIEW VISIT|KANGAROO REVIEW VISIT,BABY DELIVERY|BABY DELIVERY,MOTHER|OUTCOME,ADMIT PATIENT|ADMIT PATIENT
  clinical.encounters.sequential.list: ADMIT PATIENT,UPDATE OUTCOME MUM,ADMIT BABY,BABY DELIVERY,UPDATE BABY OUTCOME,KANGAROO REVIEW VISIT
  clinical.encounters.display.list: MOTHER|ADMIT PATIENT,UPDATE OUTCOME MUM;BABY|ADMIT BABY,BABY DELIVERY,UPDATE BABY OUTCOME,KANGAROO REVIEW VISIT
  scope: UPDATE OUTCOME MUM|,BABY DELIVERY|,BABY|,UPDATE BABY OUTCOME|,MOTHER|,ADMIT BABY|,KANGAROO REVIEW VISIT|,ADMIT PATIENT|,BABY DELIVERY COUNT|EXISTS
  concept: BABY DELIVERY COUNT|Number of babies
  label: ADMIT BABY|Admit baby,BABY DELIVERY|Baby Delivery,BABY|Baby,BABY DELIVERY COUNT|Baby Delivery Count,UPDATE OUTCOME MUM|Update Outcome Mum,MOTHER|Mother

test: &TEST
  label.encounter.map: UPDATE BABY OUTCOME|UPDATE BABY OUTCOME,BABY DELIVERY COUNT|BABY DELIVERY,ADMIT BABY|ADMIT PATIENT,UPDATE OUTCOME MUM|UPDATE OUTCOME,BABY|OUTCOME,KANGAROO REVIEW VISIT|KANGAROO REVIEW VISIT,BABY DELIVERY|BABY DELIVERY,MOTHER|OUTCOME,ADMIT PATIENT|ADMIT PATIENT
  clinical.encounters.sequential.list: ADMIT PATIENT,UPDATE OUTCOME MUM,ADMIT BABY,BABY DELIVERY,UPDATE BABY OUTCOME,KANGAROO REVIEW VISIT
  clinical.encounters.display.list: MOTHER|ADMIT PATIENT,UPDATE OUTCOME MUM;BABY|ADMIT BABY,BABY DELIVERY,UPDATE BABY OUTCOME,KANGAROO REVIEW VISIT
  scope: UPDATE OUTCOME MUM|,BABY DELIVERY|,BABY|,UPDATE BABY OUTCOME|,MOTHER|,ADMIT BABY|,KANGAROO REVIEW VISIT|,ADMIT PATIENT|,BABY DELIVERY COUNT|EXISTS
  concept: BABY DELIVERY COUNT|Number of babies
  label: ADMIT BABY|Admit baby,BABY DELIVERY|Baby Delivery,BABY|Baby,BABY DELIVERY COUNT|Baby Delivery Count,UPDATE OUTCOME MUM|Update Outcome Mum,MOTHER|Mother

