
production:
  label.encounter.map: BABY DELIVERY|BABY DELIVERY,MOTHER|OUTCOME,BABY|OUTCOME,ADMIT PATIENT|ADMIT PATIENT,BABY DELIVERY COUNT|BABY DELIVERY,KANGAROO REVIEW VISIT|KANGAROO REVIEW VISIT,ADMIT BABY|ADMIT PATIENT,UPDATE BABY OUTCOME|UPDATE BABY OUTCOME,UPDATE OUTCOME MUM|UPDATE OUTCOME
  clinical.encounters.sequential.list: ADMIT PATIENT,UPDATE OUTCOME MUM,ADMIT BABY,BABY DELIVERY,UPDATE BABY OUTCOME,KANGAROO REVIEW VISIT
  clinical.encounters.display.list: MOTHER|ADMIT PATIENT,UPDATE OUTCOME MUM;BABY|ADMIT BABY,BABY DELIVERY,UPDATE BABY OUTCOME,KANGAROO REVIEW VISIT
  scope: UPDATE BABY OUTCOME|,ADMIT BABY|,UPDATE OUTCOME MUM|,BABY DELIVERY|,BABY|,ADMIT PATIENT|,MOTHER|,BABY DELIVERY COUNT|EXISTS,KANGAROO REVIEW VISIT|
  concept: BABY DELIVERY COUNT|Number of babies
  label: BABY DELIVERY COUNT|Baby Delivery Count,MOTHER|Mother,BABY DELIVERY|Baby Delivery,BABY|Baby,ADMIT BABY|Admit baby,UPDATE OUTCOME MUM|Update Outcome Mum

development:
  label.encounter.map: BABY DELIVERY|BABY DELIVERY,MOTHER|OUTCOME,BABY|OUTCOME,ADMIT PATIENT|ADMIT PATIENT,BABY DELIVERY COUNT|BABY DELIVERY,KANGAROO REVIEW VISIT|KANGAROO REVIEW VISIT,ADMIT BABY|ADMIT PATIENT,UPDATE BABY OUTCOME|UPDATE BABY OUTCOME,UPDATE OUTCOME MUM|UPDATE OUTCOME
  clinical.encounters.sequential.list: ADMIT PATIENT,UPDATE OUTCOME MUM,ADMIT BABY,BABY DELIVERY,UPDATE BABY OUTCOME,KANGAROO REVIEW VISIT
  clinical.encounters.display.list: MOTHER|ADMIT PATIENT,UPDATE OUTCOME MUM;BABY|ADMIT BABY,BABY DELIVERY,UPDATE BABY OUTCOME,KANGAROO REVIEW VISIT
  scope: UPDATE BABY OUTCOME|,ADMIT BABY|,UPDATE OUTCOME MUM|,BABY DELIVERY|,BABY|,ADMIT PATIENT|,MOTHER|,BABY DELIVERY COUNT|EXISTS,KANGAROO REVIEW VISIT|
  concept: BABY DELIVERY COUNT|Number of babies
  label: BABY DELIVERY COUNT|Baby Delivery Count,MOTHER|Mother,BABY DELIVERY|Baby Delivery,BABY|Baby,ADMIT BABY|Admit baby,UPDATE OUTCOME MUM|Update Outcome Mum

test: &TEST
  label.encounter.map: BABY DELIVERY|BABY DELIVERY,MOTHER|OUTCOME,BABY|OUTCOME,ADMIT PATIENT|ADMIT PATIENT,BABY DELIVERY COUNT|BABY DELIVERY,KANGAROO REVIEW VISIT|KANGAROO REVIEW VISIT,ADMIT BABY|ADMIT PATIENT,UPDATE BABY OUTCOME|UPDATE BABY OUTCOME,UPDATE OUTCOME MUM|UPDATE OUTCOME
  clinical.encounters.sequential.list: ADMIT PATIENT,UPDATE OUTCOME MUM,ADMIT BABY,BABY DELIVERY,UPDATE BABY OUTCOME,KANGAROO REVIEW VISIT
  clinical.encounters.display.list: MOTHER|ADMIT PATIENT,UPDATE OUTCOME MUM;BABY|ADMIT BABY,BABY DELIVERY,UPDATE BABY OUTCOME,KANGAROO REVIEW VISIT
  scope: UPDATE BABY OUTCOME|,ADMIT BABY|,UPDATE OUTCOME MUM|,BABY DELIVERY|,BABY|,ADMIT PATIENT|,MOTHER|,BABY DELIVERY COUNT|EXISTS,KANGAROO REVIEW VISIT|
  concept: BABY DELIVERY COUNT|Number of babies
  label: BABY DELIVERY COUNT|Baby Delivery Count,MOTHER|Mother,BABY DELIVERY|Baby Delivery,BABY|Baby,ADMIT BABY|Admit baby,UPDATE OUTCOME MUM|Update Outcome Mum

