
production:
  label.encounter.map: ADMIT PATIENT|ADMIT PATIENT,BABY DELIVERY|BABY DELIVERY,MOTHER|OUTCOME,ADMIT BABY|ADMIT PATIENT,KANGAROO REVIEW VISIT|KANGAROO REVIEW VISIT,BABY|OUTCOME,UPDATE BABY OUTCOME|UPDATE BABY OUTCOME,UPDATE OUTCOME MUM|UPDATE OUTCOME
  clinical.encounters.sequential.list: ADMIT PATIENT,UPDATE OUTCOME MUM,ADMIT BABY,BABY DELIVERY,UPDATE BABY OUTCOME,KANGAROO REVIEW VISIT
  clinical.encounters.display.list: MOTHER|ADMIT PATIENT,UPDATE OUTCOME MUM;BABY|ADMIT BABY,BABY DELIVERY,UPDATE BABY OUTCOME,KANGAROO REVIEW VISIT
  scope: BABY|,MOTHER|,KANGAROO REVIEW VISIT|,BABY DELIVERY|,UPDATE OUTCOME MUM|,UPDATE BABY OUTCOME|,ADMIT BABY|,ADMIT PATIENT|
  label: MOTHER|Mother,UPDATE OUTCOME MUM|Update Outcome Mum,BABY|Baby,BABY DELIVERY|Baby Delivery,ADMIT BABY|Admit baby

development:
  label.encounter.map: ADMIT PATIENT|ADMIT PATIENT,BABY DELIVERY|BABY DELIVERY,MOTHER|OUTCOME,ADMIT BABY|ADMIT PATIENT,KANGAROO REVIEW VISIT|KANGAROO REVIEW VISIT,BABY|OUTCOME,UPDATE BABY OUTCOME|UPDATE BABY OUTCOME,UPDATE OUTCOME MUM|UPDATE OUTCOME
  clinical.encounters.sequential.list: ADMIT PATIENT,UPDATE OUTCOME MUM,ADMIT BABY,BABY DELIVERY,UPDATE BABY OUTCOME,KANGAROO REVIEW VISIT
  clinical.encounters.display.list: MOTHER|ADMIT PATIENT,UPDATE OUTCOME MUM;BABY|ADMIT BABY,BABY DELIVERY,UPDATE BABY OUTCOME,KANGAROO REVIEW VISIT
  scope: BABY|,MOTHER|,KANGAROO REVIEW VISIT|,BABY DELIVERY|,UPDATE OUTCOME MUM|,UPDATE BABY OUTCOME|,ADMIT BABY|,ADMIT PATIENT|
  label: MOTHER|Mother,UPDATE OUTCOME MUM|Update Outcome Mum,BABY|Baby,BABY DELIVERY|Baby Delivery,ADMIT BABY|Admit baby

test: &TEST
  label.encounter.map: ADMIT PATIENT|ADMIT PATIENT,BABY DELIVERY|BABY DELIVERY,MOTHER|OUTCOME,ADMIT BABY|ADMIT PATIENT,KANGAROO REVIEW VISIT|KANGAROO REVIEW VISIT,BABY|OUTCOME,UPDATE BABY OUTCOME|UPDATE BABY OUTCOME,UPDATE OUTCOME MUM|UPDATE OUTCOME
  clinical.encounters.sequential.list: ADMIT PATIENT,UPDATE OUTCOME MUM,ADMIT BABY,BABY DELIVERY,UPDATE BABY OUTCOME,KANGAROO REVIEW VISIT
  clinical.encounters.display.list: MOTHER|ADMIT PATIENT,UPDATE OUTCOME MUM;BABY|ADMIT BABY,BABY DELIVERY,UPDATE BABY OUTCOME,KANGAROO REVIEW VISIT
  scope: BABY|,MOTHER|,KANGAROO REVIEW VISIT|,BABY DELIVERY|,UPDATE OUTCOME MUM|,UPDATE BABY OUTCOME|,ADMIT BABY|,ADMIT PATIENT|
  label: MOTHER|Mother,UPDATE OUTCOME MUM|Update Outcome Mum,BABY|Baby,BABY DELIVERY|Baby Delivery,ADMIT BABY|Admit baby

mother: two_protocol_patients
admit_patient: two_protocol_patients
update_outcome_mum: two_protocol_patients
baby: two_protocol_patients
admit_baby: two_protocol_patients
baby_delivery: two_protocol_patients
update_baby_outcome: two_protocol_patients
kangaroo_review_visit: two_protocol_patients