
production:
  label.encounter.map: BABY DELIVERY COUNT|BABY DELIVERY,ADMIT BABY|ADMIT PATIENT,BABY DELIVERY|BABY DELIVERY,ADMIT PATIENT|ADMIT PATIENT,KANGAROO REVIEW VISIT|KANGAROO REVIEW VISIT,UPDATE OUTCOME MUM|UPDATE OUTCOME,UPDATE BABY OUTCOME|UPDATE BABY OUTCOME
  clinical.encounters.sequential.list: ADMIT BABY,ADMIT PATIENT,BABY DELIVERY COUNT,KANGAROO REVIEW VISIT,UPDATE BABY OUTCOME,UPDATE OUTCOME MUM
  clinical.encounters.display.list: ADMIT BABY;ADMIT PATIENT;BABY DELIVERY COUNT;KANGAROO REVIEW VISIT;UPDATE BABY OUTCOME;UPDATE OUTCOME MUM
  scope: KANGAROO REVIEW VISIT|,ADMIT PATIENT|,BABY DELIVERY COUNT|EXISTS,UPDATE OUTCOME MUM|,UPDATE BABY OUTCOME|,ADMIT BABY|,BABY DELIVERY|
  concept: BABY DELIVERY COUNT|Number of babies
  label: BABY DELIVERY COUNT|Baby Delivery Count,ADMIT BABY|Admit baby,UPDATE OUTCOME MUM|Update Outcome Mum,BABY DELIVERY|Baby Delivery

development:
  label.encounter.map: BABY DELIVERY COUNT|BABY DELIVERY,ADMIT BABY|ADMIT PATIENT,BABY DELIVERY|BABY DELIVERY,ADMIT PATIENT|ADMIT PATIENT,KANGAROO REVIEW VISIT|KANGAROO REVIEW VISIT,UPDATE OUTCOME MUM|UPDATE OUTCOME,UPDATE BABY OUTCOME|UPDATE BABY OUTCOME
  clinical.encounters.sequential.list: ADMIT BABY,ADMIT PATIENT,BABY DELIVERY COUNT,KANGAROO REVIEW VISIT,UPDATE BABY OUTCOME,UPDATE OUTCOME MUM
  clinical.encounters.display.list: ADMIT BABY;ADMIT PATIENT;BABY DELIVERY COUNT;KANGAROO REVIEW VISIT;UPDATE BABY OUTCOME;UPDATE OUTCOME MUM
  scope: KANGAROO REVIEW VISIT|,ADMIT PATIENT|,BABY DELIVERY COUNT|EXISTS,UPDATE OUTCOME MUM|,UPDATE BABY OUTCOME|,ADMIT BABY|,BABY DELIVERY|
  concept: BABY DELIVERY COUNT|Number of babies
  label: BABY DELIVERY COUNT|Baby Delivery Count,ADMIT BABY|Admit baby,UPDATE OUTCOME MUM|Update Outcome Mum,BABY DELIVERY|Baby Delivery

test: &TEST
  label.encounter.map: BABY DELIVERY COUNT|BABY DELIVERY,ADMIT BABY|ADMIT PATIENT,BABY DELIVERY|BABY DELIVERY,ADMIT PATIENT|ADMIT PATIENT,KANGAROO REVIEW VISIT|KANGAROO REVIEW VISIT,UPDATE OUTCOME MUM|UPDATE OUTCOME,UPDATE BABY OUTCOME|UPDATE BABY OUTCOME
  clinical.encounters.sequential.list: ADMIT BABY,ADMIT PATIENT,BABY DELIVERY COUNT,KANGAROO REVIEW VISIT,UPDATE BABY OUTCOME,UPDATE OUTCOME MUM
  clinical.encounters.display.list: ADMIT BABY;ADMIT PATIENT;BABY DELIVERY COUNT;KANGAROO REVIEW VISIT;UPDATE BABY OUTCOME;UPDATE OUTCOME MUM
  scope: KANGAROO REVIEW VISIT|,ADMIT PATIENT|,BABY DELIVERY COUNT|EXISTS,UPDATE OUTCOME MUM|,UPDATE BABY OUTCOME|,ADMIT BABY|,BABY DELIVERY|
  concept: BABY DELIVERY COUNT|Number of babies
  label: BABY DELIVERY COUNT|Baby Delivery Count,ADMIT BABY|Admit baby,UPDATE OUTCOME MUM|Update Outcome Mum,BABY DELIVERY|Baby Delivery

