
production:
  clinical.encounters.sequential.list: UPDATE OUTCOME MUM,BABY DELIVERY,ADMIT PATIENT,BABY DELIVERY COUNT,ADMIT BABY,KANGAROO REVIEW VISIT,UPDATE BABY OUTCOME
  scope: UPDATE OUTCOME MUM|,ADMIT PATIENT|,KANGAROO REVIEW VISIT|,BABY DELIVERY|,ADMIT BABY|,UPDATE BABY OUTCOME|,BABY DELIVERY COUNT|
  label: BABY DELIVERY|Baby Delivery,ADMIT BABY|Admit baby,BABY DELIVERY COUNT|Baby Delivery Count,UPDATE OUTCOME MUM|Update Outcome Mum

development:
  clinical.encounters.sequential.list: UPDATE OUTCOME MUM,BABY DELIVERY,ADMIT PATIENT,BABY DELIVERY COUNT,ADMIT BABY,KANGAROO REVIEW VISIT,UPDATE BABY OUTCOME
  scope: UPDATE OUTCOME MUM|,ADMIT PATIENT|,KANGAROO REVIEW VISIT|,BABY DELIVERY|,ADMIT BABY|,UPDATE BABY OUTCOME|,BABY DELIVERY COUNT|
  label: BABY DELIVERY|Baby Delivery,ADMIT BABY|Admit baby,BABY DELIVERY COUNT|Baby Delivery Count,UPDATE OUTCOME MUM|Update Outcome Mum

test: &TEST
  clinical.encounters.sequential.list: UPDATE OUTCOME MUM,BABY DELIVERY,ADMIT PATIENT,BABY DELIVERY COUNT,ADMIT BABY,KANGAROO REVIEW VISIT,UPDATE BABY OUTCOME
  scope: UPDATE OUTCOME MUM|,ADMIT PATIENT|,KANGAROO REVIEW VISIT|,BABY DELIVERY|,ADMIT BABY|,UPDATE BABY OUTCOME|,BABY DELIVERY COUNT|
  label: BABY DELIVERY|Baby Delivery,ADMIT BABY|Admit baby,BABY DELIVERY COUNT|Baby Delivery Count,UPDATE OUTCOME MUM|Update Outcome Mum

