
production:
  label.encounter.map: REFER BABY|REFERRAL,UPDATE BABY OUTCOME|UPDATE BABY OUTCOME,ADMIT BABY|ADMIT PATIENT,MOTHER|OUTCOME,ADMIT PATIENT|ADMIT PATIENT,KANGAROO REVIEW VISIT|KANGAROO REVIEW VISIT,UPDATE OUTCOME MUM|UPDATE OUTCOME,BABY DELIVERY|BABY DELIVERY,BABY|OUTCOME
  clinical.encounters.sequential.list: ADMIT PATIENT,UPDATE OUTCOME MUM,ADMIT BABY,BABY DELIVERY,REFER BABY,UPDATE BABY OUTCOME,KANGAROO REVIEW VISIT
  clinical.encounters.display.list: MOTHER|ADMIT PATIENT,UPDATE OUTCOME MUM;BABY|ADMIT BABY,BABY DELIVERY,REFER BABY,UPDATE BABY OUTCOME,KANGAROO REVIEW VISIT
  scope: UPDATE BABY OUTCOME|,BABY|,ADMIT BABY|,KANGAROO REVIEW VISIT|,REFER BABY|,UPDATE OUTCOME MUM|,MOTHER|,ADMIT PATIENT|,BABY DELIVERY|
  label: BABY|Baby,REFER BABY|Refer Baby,UPDATE OUTCOME MUM|Update Outcome Mum,ADMIT BABY|Admit baby,MOTHER|Mother,BABY DELIVERY|Baby Delivery

development:
  label.encounter.map: REFER BABY|REFERRAL,UPDATE BABY OUTCOME|UPDATE BABY OUTCOME,ADMIT BABY|ADMIT PATIENT,MOTHER|OUTCOME,ADMIT PATIENT|ADMIT PATIENT,KANGAROO REVIEW VISIT|KANGAROO REVIEW VISIT,UPDATE OUTCOME MUM|UPDATE OUTCOME,BABY DELIVERY|BABY DELIVERY,BABY|OUTCOME
  clinical.encounters.sequential.list: ADMIT PATIENT,UPDATE OUTCOME MUM,ADMIT BABY,BABY DELIVERY,REFER BABY,UPDATE BABY OUTCOME,KANGAROO REVIEW VISIT
  clinical.encounters.display.list: MOTHER|ADMIT PATIENT,UPDATE OUTCOME MUM;BABY|ADMIT BABY,BABY DELIVERY,REFER BABY,UPDATE BABY OUTCOME,KANGAROO REVIEW VISIT
  scope: UPDATE BABY OUTCOME|,BABY|,ADMIT BABY|,KANGAROO REVIEW VISIT|,REFER BABY|,UPDATE OUTCOME MUM|,MOTHER|,ADMIT PATIENT|,BABY DELIVERY|
  label: BABY|Baby,REFER BABY|Refer Baby,UPDATE OUTCOME MUM|Update Outcome Mum,ADMIT BABY|Admit baby,MOTHER|Mother,BABY DELIVERY|Baby Delivery

test: &TEST
  label.encounter.map: REFER BABY|REFERRAL,UPDATE BABY OUTCOME|UPDATE BABY OUTCOME,ADMIT BABY|ADMIT PATIENT,MOTHER|OUTCOME,ADMIT PATIENT|ADMIT PATIENT,KANGAROO REVIEW VISIT|KANGAROO REVIEW VISIT,UPDATE OUTCOME MUM|UPDATE OUTCOME,BABY DELIVERY|BABY DELIVERY,BABY|OUTCOME
  clinical.encounters.sequential.list: ADMIT PATIENT,UPDATE OUTCOME MUM,ADMIT BABY,BABY DELIVERY,REFER BABY,UPDATE BABY OUTCOME,KANGAROO REVIEW VISIT
  clinical.encounters.display.list: MOTHER|ADMIT PATIENT,UPDATE OUTCOME MUM;BABY|ADMIT BABY,BABY DELIVERY,REFER BABY,UPDATE BABY OUTCOME,KANGAROO REVIEW VISIT
  scope: UPDATE BABY OUTCOME|,BABY|,ADMIT BABY|,KANGAROO REVIEW VISIT|,REFER BABY|,UPDATE OUTCOME MUM|,MOTHER|,ADMIT PATIENT|,BABY DELIVERY|
  label: BABY|Baby,REFER BABY|Refer Baby,UPDATE OUTCOME MUM|Update Outcome Mum,ADMIT BABY|Admit baby,MOTHER|Mother,BABY DELIVERY|Baby Delivery

mother: two_protocol_patients
admit_patient: two_protocol_patients
update_outcome_mum: two_protocol_patients
baby: two_protocol_patients
admit_baby: two_protocol_patients
baby_delivery: two_protocol_patients
refer_baby: two_protocol_patients
update_baby_outcome: two_protocol_patients
kangaroo_review_visit: two_protocol_patients