
production:
  label.encounter.map: UPDATE OUTCOME MUM|UPDATE OUTCOME,MOTHER|OUTCOME,UPDATE BABY OUTCOME|UPDATE BABY OUTCOME,BABY DELIVERY COUNT|BABY DELIVERY,BABY|OUTCOME,ADMIT BABY|ADMIT PATIENT,KANGAROO REVIEW VISIT|KANGAROO REVIEW VISIT,ADMIT PATIENT|ADMIT PATIENT,BABY DELIVERY|BABY DELIVERY
  clinical.encounters.sequential.list: ADMIT PATIENT,UPDATE OUTCOME MUM,ADMIT BABY,BABY DELIVERY,UPDATE BABY OUTCOME,KANGAROO REVIEW VISIT
  clinical.encounters.display.list: MOTHER|ADMIT PATIENT,UPDATE OUTCOME MUM;BABY|ADMIT BABY,BABY DELIVERY,UPDATE BABY OUTCOME,KANGAROO REVIEW VISIT
  scope: MOTHER|,BABY|,BABY DELIVERY COUNT|EXISTS,KANGAROO REVIEW VISIT|,UPDATE OUTCOME MUM|,ADMIT BABY|,ADMIT PATIENT|,BABY DELIVERY|,UPDATE BABY OUTCOME|
  concept: BABY DELIVERY COUNT|Number of babies
  label: BABY|Baby,UPDATE OUTCOME MUM|Update Outcome Mum,MOTHER|Mother,ADMIT BABY|Admit baby,BABY DELIVERY COUNT|Baby Delivery Count,BABY DELIVERY|Baby Delivery

development:
  label.encounter.map: UPDATE OUTCOME MUM|UPDATE OUTCOME,MOTHER|OUTCOME,UPDATE BABY OUTCOME|UPDATE BABY OUTCOME,BABY DELIVERY COUNT|BABY DELIVERY,BABY|OUTCOME,ADMIT BABY|ADMIT PATIENT,KANGAROO REVIEW VISIT|KANGAROO REVIEW VISIT,ADMIT PATIENT|ADMIT PATIENT,BABY DELIVERY|BABY DELIVERY
  clinical.encounters.sequential.list: ADMIT PATIENT,UPDATE OUTCOME MUM,ADMIT BABY,BABY DELIVERY,UPDATE BABY OUTCOME,KANGAROO REVIEW VISIT
  clinical.encounters.display.list: MOTHER|ADMIT PATIENT,UPDATE OUTCOME MUM;BABY|ADMIT BABY,BABY DELIVERY,UPDATE BABY OUTCOME,KANGAROO REVIEW VISIT
  scope: MOTHER|,BABY|,BABY DELIVERY COUNT|EXISTS,KANGAROO REVIEW VISIT|,UPDATE OUTCOME MUM|,ADMIT BABY|,ADMIT PATIENT|,BABY DELIVERY|,UPDATE BABY OUTCOME|
  concept: BABY DELIVERY COUNT|Number of babies
  label: BABY|Baby,UPDATE OUTCOME MUM|Update Outcome Mum,MOTHER|Mother,ADMIT BABY|Admit baby,BABY DELIVERY COUNT|Baby Delivery Count,BABY DELIVERY|Baby Delivery

test: &TEST
  label.encounter.map: UPDATE OUTCOME MUM|UPDATE OUTCOME,MOTHER|OUTCOME,UPDATE BABY OUTCOME|UPDATE BABY OUTCOME,BABY DELIVERY COUNT|BABY DELIVERY,BABY|OUTCOME,ADMIT BABY|ADMIT PATIENT,KANGAROO REVIEW VISIT|KANGAROO REVIEW VISIT,ADMIT PATIENT|ADMIT PATIENT,BABY DELIVERY|BABY DELIVERY
  clinical.encounters.sequential.list: ADMIT PATIENT,UPDATE OUTCOME MUM,ADMIT BABY,BABY DELIVERY,UPDATE BABY OUTCOME,KANGAROO REVIEW VISIT
  clinical.encounters.display.list: MOTHER|ADMIT PATIENT,UPDATE OUTCOME MUM;BABY|ADMIT BABY,BABY DELIVERY,UPDATE BABY OUTCOME,KANGAROO REVIEW VISIT
  scope: MOTHER|,BABY|,BABY DELIVERY COUNT|EXISTS,KANGAROO REVIEW VISIT|,UPDATE OUTCOME MUM|,ADMIT BABY|,ADMIT PATIENT|,BABY DELIVERY|,UPDATE BABY OUTCOME|
  concept: BABY DELIVERY COUNT|Number of babies
  label: BABY|Baby,UPDATE OUTCOME MUM|Update Outcome Mum,MOTHER|Mother,ADMIT BABY|Admit baby,BABY DELIVERY COUNT|Baby Delivery Count,BABY DELIVERY|Baby Delivery

