
production:
  label.encounter.map: UPDATE BABY OUTCOME|UPDATE BABY OUTCOME,BABY|OUTCOME,BABY DELIVERY COUNT|BABY DELIVERY,ADMIT BABY|ADMIT PATIENT,MOTHER|OUTCOME,BABY DELIVERY|BABY DELIVERY,UPDATE OUTCOME MUM|UPDATE OUTCOME,KANGAROO REVIEW VISIT|KANGAROO REVIEW VISIT,ADMIT PATIENT|ADMIT PATIENT
  clinical.encounters.sequential.list: ADMIT PATIENT,UPDATE OUTCOME MUM,ADMIT BABY,BABY DELIVERY,UPDATE BABY OUTCOME,KANGAROO REVIEW VISIT
  clinical.encounters.display.list: ADMIT PATIENT;MOTHER|UPDATE OUTCOME MUM;BABY|ADMIT BABY,BABY DELIVERY,UPDATE BABY OUTCOME,KANGAROO REVIEW VISIT
  scope: BABY|,ADMIT PATIENT|,KANGAROO REVIEW VISIT|,BABY DELIVERY|,ADMIT BABY|,UPDATE OUTCOME MUM|,UPDATE BABY OUTCOME|,MOTHER|,BABY DELIVERY COUNT|EXISTS
  concept: BABY DELIVERY COUNT|Number of babies
  label: ADMIT BABY|Admit baby,BABY|Baby,UPDATE OUTCOME MUM|Update Outcome Mum,BABY DELIVERY|Baby Delivery,MOTHER|Mother,BABY DELIVERY COUNT|Baby Delivery Count

development:
  label.encounter.map: UPDATE BABY OUTCOME|UPDATE BABY OUTCOME,BABY|OUTCOME,BABY DELIVERY COUNT|BABY DELIVERY,ADMIT BABY|ADMIT PATIENT,MOTHER|OUTCOME,BABY DELIVERY|BABY DELIVERY,UPDATE OUTCOME MUM|UPDATE OUTCOME,KANGAROO REVIEW VISIT|KANGAROO REVIEW VISIT,ADMIT PATIENT|ADMIT PATIENT
  clinical.encounters.sequential.list: ADMIT PATIENT,UPDATE OUTCOME MUM,ADMIT BABY,BABY DELIVERY,UPDATE BABY OUTCOME,KANGAROO REVIEW VISIT
  clinical.encounters.display.list: ADMIT PATIENT;MOTHER|UPDATE OUTCOME MUM;BABY|ADMIT BABY,BABY DELIVERY,UPDATE BABY OUTCOME,KANGAROO REVIEW VISIT
  scope: BABY|,ADMIT PATIENT|,KANGAROO REVIEW VISIT|,BABY DELIVERY|,ADMIT BABY|,UPDATE OUTCOME MUM|,UPDATE BABY OUTCOME|,MOTHER|,BABY DELIVERY COUNT|EXISTS
  concept: BABY DELIVERY COUNT|Number of babies
  label: ADMIT BABY|Admit baby,BABY|Baby,UPDATE OUTCOME MUM|Update Outcome Mum,BABY DELIVERY|Baby Delivery,MOTHER|Mother,BABY DELIVERY COUNT|Baby Delivery Count

test: &TEST
  label.encounter.map: UPDATE BABY OUTCOME|UPDATE BABY OUTCOME,BABY|OUTCOME,BABY DELIVERY COUNT|BABY DELIVERY,ADMIT BABY|ADMIT PATIENT,MOTHER|OUTCOME,BABY DELIVERY|BABY DELIVERY,UPDATE OUTCOME MUM|UPDATE OUTCOME,KANGAROO REVIEW VISIT|KANGAROO REVIEW VISIT,ADMIT PATIENT|ADMIT PATIENT
  clinical.encounters.sequential.list: ADMIT PATIENT,UPDATE OUTCOME MUM,ADMIT BABY,BABY DELIVERY,UPDATE BABY OUTCOME,KANGAROO REVIEW VISIT
  clinical.encounters.display.list: ADMIT PATIENT;MOTHER|UPDATE OUTCOME MUM;BABY|ADMIT BABY,BABY DELIVERY,UPDATE BABY OUTCOME,KANGAROO REVIEW VISIT
  scope: BABY|,ADMIT PATIENT|,KANGAROO REVIEW VISIT|,BABY DELIVERY|,ADMIT BABY|,UPDATE OUTCOME MUM|,UPDATE BABY OUTCOME|,MOTHER|,BABY DELIVERY COUNT|EXISTS
  concept: BABY DELIVERY COUNT|Number of babies
  label: ADMIT BABY|Admit baby,BABY|Baby,UPDATE OUTCOME MUM|Update Outcome Mum,BABY DELIVERY|Baby Delivery,MOTHER|Mother,BABY DELIVERY COUNT|Baby Delivery Count

